// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/hello.proto

package proto

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Hello service

func NewHelloEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Hello service

type HelloService interface {
	SayHelloWithoutTime(ctx context.Context, in *HelloRequestWithoutTime, opts ...client.CallOption) (*HelloResponseWithoutTime, error)
	SayHelloWithTime(ctx context.Context, in *HelloRequestWithTime, opts ...client.CallOption) (*HelloResponseWithTime, error)
}

type helloService struct {
	c    client.Client
	name string
}

func NewHelloService(name string, c client.Client) HelloService {
	return &helloService{
		c:    c,
		name: name,
	}
}

func (c *helloService) SayHelloWithoutTime(ctx context.Context, in *HelloRequestWithoutTime, opts ...client.CallOption) (*HelloResponseWithoutTime, error) {
	req := c.c.NewRequest(c.name, "Hello.SayHelloWithoutTime", in)
	out := new(HelloResponseWithoutTime)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloService) SayHelloWithTime(ctx context.Context, in *HelloRequestWithTime, opts ...client.CallOption) (*HelloResponseWithTime, error) {
	req := c.c.NewRequest(c.name, "Hello.SayHelloWithTime", in)
	out := new(HelloResponseWithTime)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Hello service

type HelloHandler interface {
	SayHelloWithoutTime(context.Context, *HelloRequestWithoutTime, *HelloResponseWithoutTime) error
	SayHelloWithTime(context.Context, *HelloRequestWithTime, *HelloResponseWithTime) error
}

func RegisterHelloHandler(s server.Server, hdlr HelloHandler, opts ...server.HandlerOption) error {
	type hello interface {
		SayHelloWithoutTime(ctx context.Context, in *HelloRequestWithoutTime, out *HelloResponseWithoutTime) error
		SayHelloWithTime(ctx context.Context, in *HelloRequestWithTime, out *HelloResponseWithTime) error
	}
	type Hello struct {
		hello
	}
	h := &helloHandler{hdlr}
	return s.Handle(s.NewHandler(&Hello{h}, opts...))
}

type helloHandler struct {
	HelloHandler
}

func (h *helloHandler) SayHelloWithoutTime(ctx context.Context, in *HelloRequestWithoutTime, out *HelloResponseWithoutTime) error {
	return h.HelloHandler.SayHelloWithoutTime(ctx, in, out)
}

func (h *helloHandler) SayHelloWithTime(ctx context.Context, in *HelloRequestWithTime, out *HelloResponseWithTime) error {
	return h.HelloHandler.SayHelloWithTime(ctx, in, out)
}
